name: Build and Run Docker Container

on:
  push:
    branches:
      - main  # or replace with your desired branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker build -t local-app:latest .

    - name: Run Docker container
      run: |
        docker run -d -p 5001:5001 --name running-app local-app:latest

    - name: Check container logs
      run: |
        sleep 5
        docker logs running-app

    - name: Cleanup
      if: always()
      run: |
        docker stop running-app
        docker rm running-app
